# Generated by Django 5.0.6 on 2024-06-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carnetgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
